name: Feature Request
description: Request a new feature or enhancement
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Describe the feature you'd like to see implemented.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature
      placeholder: "Describe the feature..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / User Story
      description: Why is this feature needed? What problem does it solve?
      placeholder: "As a [user], I want [feature] so that [benefit]..."
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List specific requirements or acceptance criteria
      placeholder: |
        - Requirement 1
        - Requirement 2
        - Requirement 3
    validations:
      required: true

  - type: dropdown
    id: workspace
    attributes:
      label: Target Workspace
      description: Which workspace(s) will this feature affect?
      options:
        - client
        - server
        - shared
        - multiple
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information, mockups, or references
